### ISSUE TITLE
`scan failed to produce proper report` for repos without vulnerabilities

### ISSUE THREAD

**Issue by Akaame** [Templum/govulncheck-action#11]
```
govulncheck ./... 
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
No vulnerabilities found.
```

For this repo with no vulnerabilities the following error is printed out from the action:

 `ERR Scanning yielded error error="scan failed to produce proper report".`
 
```yaml
steps:
      - uses: actions/checkout@v3
      - uses: Templum/govulncheck-action@v0.0.5
```

Would it be possible to check the action behavior for a clean repo?
