### ISSUE TITLE
[BUG] Latest govulncheck breaks action

### ISSUE THREAD

**Issue by srebhan** [Templum/govulncheck-action#33]
Using the latest govulncheck (`v0.0.0-20230325131008-9550759f8614`) breaks the action (`Templum/govulncheck-action@v0.10.0`) as the output JSON format changed for govulncheck (likely in [this commit](https://github.com/golang/vuln/commit/13f948732dfef618d28bcecea540bb951e08e739)).

### Config:
```yaml  
name: govulncheck
on:
  push:
    branches:
      - master
  schedule:
    # Trigger every day at 16:00 UTC
    - cron: '0 16 * * *'
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v0.10.0
        with:
          go-version: '1.20'
          vulncheck-version: latest
          package: ./...
```

### Logs:

```text
2023-03-27T12:14:33.7129890Z 12:14PM INF GoEnvironment Details: GOPRIVATE= Go-Arch=amd64 Go-Os=linux Go-Version=go1.20.2
2023-03-27T12:14:33.7130490Z 12:14PM INF Running govulncheck for package ./... in dir /github/workspace
2023-03-27T12:16:01.8559000Z 12:16PM ERR parsing govulncheck output yielded error error="invalid character '{' after top-level value"
2023-03-27T12:16:01.8562263Z 12:16PM ERR Scanning yielded error error="scan failed to produce proper report"
2023-03-27T12:16:10.1737233Z Error: Process completed with exit code 2.
```

You can find the full output [here](https://github.com/influxdata/telegraf/actions/runs/4532271451/jobs/7983445462#step:3:21).

### Details:

The output format of govulncheck seemingly changed between `golang.org/x/vuln/cmd/govulncheck@fd6b8605e1743f75db7cd8db18cc54c169edef6e` (known good) and the current version, likely due to the commit above. Before the output was

```json
{
        "Vulns": null
}
```
while the output of the latest version looks like this

```json
{
  "preamble": {
    "go_version": "go1.20.2",
    "tool_version": "govulncheck@v0.0.0",
    "db": "https://vuln.go.dev",
    "db_last_modified": "2023-03-27T17:34:34Z",
    "query_kind": "Source",
    "callstack_mode": "Compact"
  }
}
{
  "progress": "Scanning your code and 1929 packages across 415 dependent modules for known vulnerabilities..."
}
```
